title: Quran Web3
description: Decentralized Quran & NFT Project Updates
baseurl: "" # Biarkan kosong jika menggunakan domain utama / custom domain
url: "https://quran-web3.github.io" # Sesuaikan dengan URL GitHub Pages Anda

# Konfigurasi Markdown & Permalinks
markdown: kramdown
permalink: /blog/:title/

# Mengabaikan folder node atau vendor jika ada
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
